sudo: required

language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - nightly

services:
  - docker

before_install:
  - docker-compose run --rm composer composer install

script:
  - docker-compose run --rm composer ./vendor/bin/phpunit
