language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - nightly

before_install:
  - travis_retry composer self-update
  - travis_retry composer install

script:
  - ./vendor/bin/phpunit

after_script:
  - ./vendor/bin/coveralls -v
